Fix orbcorr cavity
lnls-fac/apsuite pull request #286
Opened 2024-11-21 13:19 UTC by Gabrielrezende-asc

A possible problem in the orbit correction class:
1) The cavity was always being set as True regardless of the initial state of the model, and the original state was not being restored.
2) The cavity must be set to True when calculating the kicks to correct the orbit if we choose to use the RF correction, so I added a line to set the cavity to True in this function and then restore the original value.

2024-11-22 11:49 UTC, xresende commented
should we keep modifying the model under the hood for the use of algorithms to make sense or should we raise an explanatory exception educating the user on the propor use of the algorithm ? 

@murilobalves , @fernandohds564 , @vellosok75 , @Gabrielrezende-asc 

another concern: potential inconsistencies because of temporary modifications of the model when threads that use the model are running.

2024-11-22 12:56 UTC, fernandohds564 commented
I think we should drop this behavior and raise exceptions when the model state doesn't match what is expected.

2025-03-27 13:41 UTC, xresende commented
@Gabrielrezende-asc 

> I think we should drop this behavior and raise exceptions when the model state doesn't match what is expected.

agreed

2025-03-27 13:42 UTC, xresende commented
@murilobalves , @vellosok75 , do you want to take a position on this ?

@Gabrielrezende-asc , if others do not object, I think we can proceed with what fernando and I agreed.

2025-03-27 13:44 UTC, xresende requested changes
If no one object we should implement what was discussed in the conversation.

2025-04-01 11:47 UTC, vellosok75 commented
> @murilobalves , @vellosok75 , do you want to take a position on this ?
> 
> @Gabrielrezende-asc , if others do not object, I think we can proceed with what fernando and I agreed.

I agree. I prefer raising exceptions.

2025-04-01 11:58 UTC, vellosok75 commented on apsuite/orbcorr/orbit_correction.py
>      def set_kicks(self, kicks):
Also, shouldn't we be working with the `set_delta_kicks` method in `correct_orbit`? I believe the `set_kicks` is incorrect since the pseudo-inversion is giving us deltas, right?

2025-04-07 18:41 UTC, murilobalves commented
> should we keep modifying the model under the hood for the use of algorithms to make sense or should we raise an explanatory exception educating the user on the propor use of the algorithm ?
> 
> @murilobalves , @fernandohds564 , @vellosok75 , @Gabrielrezende-asc
> 
> another concern: potential inconsistencies because of temporary modifications of the model when threads that use the same model are running.

I agree with raising exceptions.

2025-04-11 11:22 UTC, Gabrielrezende-asc commented
Ok guys, as soon as I finish tasks related to the VPU commissioning I will continue this PR

2025-05-05 13:28 UTC, fernandohds564 commented on apsuite/orbcorr/orbit_correction.py
> +                            " to be used in correction..")
I think `Exception` is too general. What do you think of the suggestion below?
```suggestion
            raise ValueError(
                "It is necessary to turn on the cavity if it is "
                "to be used in correction."
            )
```

2025-05-09 11:28 UTC, murilobalves approved these changes

2025-06-18 12:13 UTC, merged